# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import sentence_gen_pb2 as sentence__gen__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    import warnings
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sentence_gen_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SentenceGenStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GenerateSentence = channel.unary_unary(
                '/sentencegen.SentenceGen/GenerateSentence',
                request_serializer=sentence__gen__pb2.GenerateSentenceRequest.SerializeToString,
                response_deserializer=sentence__gen__pb2.GenerateSentenceResponse.FromString,
                _registered_method=True)
        self.Translate = channel.unary_unary(
                '/sentencegen.SentenceGen/Translate',
                request_serializer=sentence__gen__pb2.TranslateRequest.SerializeToString,
                response_deserializer=sentence__gen__pb2.TranslateResponse.FromString,
                _registered_method=True)
        self.GenerateDefinition = channel.unary_unary(
                '/sentencegen.SentenceGen/GenerateDefinition',
                request_serializer=sentence__gen__pb2.GenerateDefinitionRequest.SerializeToString,
                response_deserializer=sentence__gen__pb2.GenerateDefinitionResponse.FromString,
                _registered_method=True)


class SentenceGenServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GenerateSentence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Translate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateDefinition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SentenceGenServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GenerateSentence': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateSentence,
                    request_deserializer=sentence__gen__pb2.GenerateSentenceRequest.FromString,
                    response_serializer=sentence__gen__pb2.GenerateSentenceResponse.SerializeToString,
            ),
            'Translate': grpc.unary_unary_rpc_method_handler(
                    servicer.Translate,
                    request_deserializer=sentence__gen__pb2.TranslateRequest.FromString,
                    response_serializer=sentence__gen__pb2.TranslateResponse.SerializeToString,
            ),
            'GenerateDefinition': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateDefinition,
                    request_deserializer=sentence__gen__pb2.GenerateDefinitionRequest.FromString,
                    response_serializer=sentence__gen__pb2.GenerateDefinitionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sentencegen.SentenceGen', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sentencegen.SentenceGen', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SentenceGen(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GenerateSentence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentencegen.SentenceGen/GenerateSentence',
            sentence__gen__pb2.GenerateSentenceRequest.SerializeToString,
            sentence__gen__pb2.GenerateSentenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Translate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentencegen.SentenceGen/Translate',
            sentence__gen__pb2.TranslateRequest.SerializeToString,
            sentence__gen__pb2.TranslateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateDefinition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sentencegen.SentenceGen/GenerateDefinition',
            sentence__gen__pb2.GenerateDefinitionRequest.SerializeToString,
            sentence__gen__pb2.GenerateDefinitionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
