# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sentence-gen.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
try:
    _runtime_version.ValidateProtobufRuntimeVersion(
        _runtime_version.Domain.PUBLIC,
        6,
        31,
        1,
        '',
        'sentence-gen.proto'
    )
except Exception:
    pass
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12sentence-gen.proto\x12\x0bsentencegen\"\x15\n\x05\x41udio\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\xb8\x01\n\x17GenerateSentenceRequest\x12\x15\n\rword_language\x18\x01 \x01(\t\x12\x1c\n\x14translation_language\x18\x02 \x01(\t\x12\x0c\n\x04word\x18\x03 \x01(\t\x12\x18\n\x10translation_hint\x18\x04 \x01(\t\x12\x15\n\rinclude_audio\x18\x05 \x01(\x08\x12)\n\x0cvoice_gender\x18\x06 \x01(\x0e\x32\x13.sentencegen.Gender\"u\n\x18GenerateSentenceResponse\x12\x19\n\x11original_sentence\x18\x01 \x01(\t\x12\x1b\n\x13translated_sentence\x18\x02 \x01(\t\x12!\n\x05\x61udio\x18\x03 \x01(\x0b\x32\x12.sentencegen.Audio\"\x96\x01\n\x19GenerateDefinitionRequest\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0c\n\x04word\x18\x02 \x01(\t\x12\x17\n\x0f\x64\x65\x66inition_hint\x18\x03 \x01(\t\x12\x15\n\rinclude_audio\x18\x04 \x01(\x08\x12)\n\x0cvoice_gender\x18\x05 \x01(\x0e\x32\x13.sentencegen.Gender\"S\n\x1aGenerateDefinitionResponse\x12\x12\n\ndefinition\x18\x01 \x01(\t\x12!\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x12.sentencegen.Audio\"\xa8\x01\n\x10TranslateRequest\x12\x15\n\rfrom_language\x18\x01 \x01(\t\x12\x13\n\x0bto_language\x18\x02 \x01(\t\x12\x0c\n\x04word\x18\x03 \x01(\t\x12\x18\n\x10translation_hint\x18\x04 \x01(\t\x12\x15\n\rinclude_audio\x18\x05 \x01(\x08\x12)\n\x0cvoice_gender\x18\x06 \x01(\x0e\x32\x13.sentencegen.Gender\"K\n\x11TranslateResponse\x12\x13\n\x0btranslation\x18\x01 \x01(\t\x12!\n\x05\x61udio\x18\x02 \x01(\x0b\x32\x12.sentencegen.Audio*,\n\x06Gender\x12\x11\n\rGENDER_FEMALE\x10\x00\x12\x0f\n\x0bGENDER_MALE\x10\x01\x32\xa1\x02\n\x0bSentenceGen\x12_\n\x10GenerateSentence\x12$.sentencegen.GenerateSentenceRequest\x1a%.sentencegen.GenerateSentenceResponse\x12J\n\tTranslate\x12\x1d.sentencegen.TranslateRequest\x1a\x1e.sentencegen.TranslateResponse\x12\x65\n\x12GenerateDefinition\x12&.sentencegen.GenerateDefinitionRequest\x1a\'.sentencegen.GenerateDefinitionResponseB\x0eZ\x0c\x63lient/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sentence_gen_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014client/proto'
  _globals['_GENDER']._serialized_start=850
  _globals['_GENDER']._serialized_end=894
  _globals['_AUDIO']._serialized_start=35
  _globals['_AUDIO']._serialized_end=56
  _globals['_GENERATESENTENCEREQUEST']._serialized_start=59
  _globals['_GENERATESENTENCEREQUEST']._serialized_end=243
  _globals['_GENERATESENTENCERESPONSE']._serialized_start=245
  _globals['_GENERATESENTENCERESPONSE']._serialized_end=362
  _globals['_GENERATEDEFINITIONREQUEST']._serialized_start=365
  _globals['_GENERATEDEFINITIONREQUEST']._serialized_end=515
  _globals['_GENERATEDEFINITIONRESPONSE']._serialized_start=517
  _globals['_GENERATEDEFINITIONRESPONSE']._serialized_end=600
  _globals['_TRANSLATEREQUEST']._serialized_start=603
  _globals['_TRANSLATEREQUEST']._serialized_end=771
  _globals['_TRANSLATERESPONSE']._serialized_start=773
  _globals['_TRANSLATERESPONSE']._serialized_end=848
  _globals['_SENTENCEGEN']._serialized_start=897
  _globals['_SENTENCEGEN']._serialized_end=1186
# @@protoc_insertion_point(module_scope)
