# Languages that have Chirp3-HD voice support (matches Go english.go)
LANGUAGES = [
    ("Arabic", "ar-XA"),
    ("Bengali (India)", "bn-IN"),
    ("Bulgarian", "bg-BG"),
    ("Chinese (Hong Kong)", "yue-HK"),
    ("Chinese (Mandarin)", "cmn-CN"),
    ("Croatian", "hr-HR"),
    ("Czech", "cs-CZ"),
    ("Danish", "da-DK"),
    ("Dutch (Belgium)", "nl-BE"),
    ("Dutch (Netherlands)", "nl-NL"),
    ("English (US)", "en-US"),
    ("English (Australia)", "en-AU"),
    ("English (India)", "en-IN"),
    ("English (UK)", "en-GB"),
    ("Estonian", "et-EE"),
    ("Finnish", "fi-FI"),
    ("French", "fr-FR"),
    ("French (Canada)", "fr-CA"),
    ("German", "de-DE"),
    ("Greek", "el-GR"),
    ("Gujarati (India)", "gu-IN"),
    ("Hebrew", "he-IL"),
    ("Hindi (India)", "hi-IN"),
    ("Hungarian", "hu-HU"),
    ("Indonesian", "id-ID"),
    ("Italian", "it-IT"),
    ("Japanese", "ja-JP"),
    ("Kannada (India)", "kn-IN"),
    ("Korean", "ko-KR"),
    ("Latvian", "lv-LV"),
    ("Lithuanian", "lt-LT"),
    ("Malayalam (India)", "ml-IN"),
    ("Marathi (India)", "mr-IN"),
    ("Norwegian Bokmål", "nb-NO"),
    ("Polish", "pl-PL"),
    ("Portuguese (Brazil)", "pt-BR"),
    ("Punjabi (India)", "pa-IN"),
    ("Romanian", "ro-RO"),
    ("Russian", "ru-RU"),
    ("Serbian", "sr-RS"),
    ("Slovak", "sk-SK"),
    ("Slovenian", "sl-SI"),
    ("Spanish", "es-ES"),
    ("Spanish (US)", "es-US"),
    ("Swahili", "sw-KE"),
    ("Swedish", "sv-SE"),
    ("Tamil (India)", "ta-IN"),
    ("Telugu (India)", "te-IN"),
    ("Thai", "th-TH"),
    ("Turkish", "tr-TR"),
    ("Ukrainian", "uk-UA"),
    ("Urdu (India)", "ur-IN"),
    ("Vietnamese", "vi-VN"),
]

LANGUAGE_NAMES = [name for name, _ in LANGUAGES]
_CODE_MAP = {name: code for name, code in LANGUAGES}


def get_language_code(display_name):
    return _CODE_MAP.get(display_name)
